version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - automation
      - dependabot
      - aws
    allow:
      - dependency-name: "github.com/aws/aws-sdk-go-v2/*"
    open-pull-requests-limit: 1
    groups:
      aws-sdk:
        patterns:
          - "github.com/aws/aws-sdk-go-v2/*"


# ---
# version: 2
# updates:
#   - package-ecosystem: "gomod"
#     directory: "/"
#     schedule:
#       interval: "daily"
#     labels:
#       - automation
#       - dependabot
#       # The `aws` label enables optional 
#       # stages in the CI for AWS cloud testing.
#       - aws
#     groups:
#       aws-sdk:
#         patterns:
#           - "github.com/aws/aws-sdk-go-v2/*"
